### ISSUE TITLE
Error when uploading

### ISSUE THREAD

**Issue by by-pm** [ESPWortuhr/Multilayout-ESP-Wordclock#161]
Hi,

I get the following error when trying ot upload to my esp. Can anyone help me?

`Traceback (most recent call last):
  File "C:\Users\pmatla\.platformio\packages\tool-esptoolpy\esptool.py", line 376, in command
    self.write(pkt)
  File "C:\Users\pmatla\.platformio\packages\tool-esptoolpy\esptool.py", line 339, in write
    self._port.write(buf)
  File "C:\Users\pmatla\.platformio\penv\lib\site-packages\serial\serialwin32.py", line 325, in write
    raise SerialTimeoutException('Write timeout')
serial.serialutil.SerialTimeoutException: Write timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pmatla\.platformio\packages\tool-esptoolpy\esptool.py", line 3969, in <module>
    _main()
  File "C:\Users\pmatla\.platformio\packages\tool-esptoolpy\esptool.py", line 3962, in _main
    main()
  File "C:\Users\pmatla\.platformio\packages\tool-esptoolpy\esptool.py", line 3604, in main
    operation_func(esp, args)
  File "C:\Users\pmatla\.platformio\packages\tool-esptoolpy\esptool.py", line 2987, in write_flash
    esp.flash_defl_block(block, seq, timeout=DEFAULT_TIMEOUT * ratio * 2)
  File "C:\Users\pmatla\.platformio\packages\tool-esptoolpy\esptool.py", line 113, in inner
    return func(*args, **kwargs)
  File "C:\Users\pmatla\.platformio\packages\tool-esptoolpy\esptool.py", line 761, in flash_defl_block
    self.check_command("write compressed data to flash after seq %d" % seq,
  File "C:\Users\pmatla\.platformio\packages\tool-esptoolpy\esptool.py", line 413, in check_command
    val, data = self.command(op, data, chk, timeout=timeout)
  File "C:\Users\pmatla\.platformio\packages\tool-esptoolpy\esptool.py", line 402, in command
    self._port.timeout = saved_timeout
  File "C:\Users\pmatla\.platformio\penv\lib\site-packages\serial\serialutil.py", line 372, in timeout
    self._reconfigure_port()
  File "C:\Users\pmatla\.platformio\penv\lib\site-packages\serial\serialwin32.py", line 222, in _reconfigure_port    
    raise SerialException(
serial.serialutil.SerialException: Cannot configure port, something went wrong. Original message: PermissionError(13, 'Toegang geweigerd.', None, 5)
*** [upload] Error 1
============================================ [FAILED] Took 21.51 seconds ============================================The terminal process "C:\Users\pmatla\.platformio\penv\Scripts\platformio.exe 'run', '--target', 'upload', '--environment', 'nodemcuv2'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
`

**Comment by dbambus** [comment]
Hey @pienmatla, 

this problem should be related to your Hardware setup. A timeout basically indicates that the connection between your USB Serial interpreter and the MCU is brocken. Either you switched RX and TX oer the MCU is not in Flashing mode.

David
