### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/home/christoph/Wortuhr/.pio/build/nodemcuv2/.sconsign310.tmp'

### ISSUE THREAD

**Issue by SkylightXD** [ESPWortuhr/Multilayout-ESP-Wordclock#410]
Hallo zusammen,

habt ihr eine Idee, was hier flasch läuft? :( 

~/Wortuhr$ pio run -t upload
Processing nodemcuv2 (platform: espressif8266; board: nodemcuv2; framework: arduino)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/nodemcuv2.html
PLATFORM: Espressif 8266 (4.2.1) > NodeMCU 1.0 (ESP-12E Module)
HARDWARE: ESP8266 160MHz, 80KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 @ 3.30102.0 (3.1.2) 
 - tool-esptool @ 1.413.0 (4.13) 
 - tool-esptoolpy @ 1.30000.201119 (3.0.0) 
 - tool-mklittlefs @ 1.203.210628 (2.3) 
 - tool-mkspiffs @ 1.200.0 (2.0) 
 - toolchain-xtensa @ 2.100300.220621 (10.3.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 45 compatible libraries
Scanning dependencies...
Dependency Graph
|-- NeoPixelBus @ 2.8.0
|-- ArduinoJson @ 6.21.5
|-- WebSockets @ 2.4.1
|-- RTClib @ 1.14.2
|-- PubSubClient @ 2.8.0
|-- WiFiManager @ 2.0.17+sha.d82d0a1
|-- DNSServer @ 1.1.0
|-- ESP8266HTTPUpdateServer @ 1.0
|-- ESP8266WebServer @ 1.0
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- Hash @ 1.0
|-- Wire @ 1.0
|-- EEPROM @ 1.0
Building in release mode
npx --no-install grunt build
*** [.pio/build/nodemcuv2/lib856] /home/christoph/Wortuhr/.pio/build/nodemcuv2/lib856: Permission denied
Running "eslint:files" (eslint) task

Running "csslint:files" (csslint) task
Linting webpage/style.css...ERROR
[L496:C5]
WARNING: Use of !important Be careful when using !important declaration (important) Browsers: All
[L497:C5]
WARNING: Use of !important Be careful when using !important declaration (important) Browsers: All
[L504:C5]
WARNING: Unknown property 'grid-gap'. Properties should be known (listed in CSS3 specification) or be a vendor-prefixed property. (known-properties) Browsers: All
>> 1 file lint free.

Running "htmllint:files" (htmllint) task
>> encountered 0 errors in total
>> 0 file(s) had lint error out of 1 file(s). (skipped 0 files)

Running "clean:temp" (clean) task
>> 0 paths cleaned.

Running "cssmin:dev" (cssmin) task
Warning: Unable to create directory ".pio/build/webpage" (Error code: EACCES). Use --force to continue.

Aborted due to warnings.
*** [include/WebPageContent.gen.inc] Error 3
PermissionError: [Errno 13] Permission denied: '/home/christoph/Wortuhr/.pio/build/nodemcuv2/.sconsign310.tmp':
  File "/home/christoph/.platformio/packages/tool-scons/scons-local-4.7.0/SCons/Script/Main.py", line 1477:
    _exec_main(parser, values)
  File "/home/christoph/.platformio/packages/tool-scons/scons-local-4.7.0/SCons/Script/Main.py", line 1431:
    _main(parser)
  File "/home/christoph/.platformio/packages/tool-scons/scons-local-4.7.0/SCons/Script/Main.py", line 1174:
    nodes = _build_targets(fs, options, targets, target_top)
  File "/home/christoph/.platformio/packages/tool-scons/scons-local-4.7.0/SCons/Script/Main.py", line 1369:
    jobs.run(postfunc = jobs_postfunc)
  File "/home/christoph/.platformio/packages/tool-scons/scons-local-4.7.0/SCons/Taskmaster/Job.py", line 114:
    postfunc()
  File "/home/christoph/.platformio/packages/tool-scons/scons-local-4.7.0/SCons/Script/Main.py", line 1366:
    SCons.SConsign.write()
  File "/home/christoph/.platformio/packages/tool-scons/scons-local-4.7.0/SCons/SConsign.py", line 131:
    syncmethod()
  File "/home/christoph/.platformio/packages/tool-scons/scons-local-4.7.0/SCons/dblite.py", line 195:
    with self._open(self._tmp_name, "wb", opener=self.opener) as f:
  File "/home/christoph/.platformio/packages/tool-scons/scons-local-4.7.0/SCons/dblite.py", line 177:
    return os.open(path, flags, mode=self._mode)
Exception ignored in: <function _Dblite.__del__ at 0x785de3bbef80>
Traceback (most recent call last):
  File "/home/christoph/.platformio/packages/tool-scons/scons-local-4.7.0/SCons/dblite.py", line 184, in __del__
  File "/home/christoph/.platformio/packages/tool-scons/scons-local-4.7.0/SCons/dblite.py", line 181, in close
  File "/home/christoph/.platformio/packages/tool-scons/scons-local-4.7.0/SCons/dblite.py", line 195, in sync
  File "/home/christoph/.platformio/packages/tool-scons/scons-local-4.7.0/SCons/dblite.py", line 177, in opener
PermissionError: [Errno 13] Permission denied: '/home/christoph/Wortuhr/.pio/build/nodemcuv2/.sconsign310.tmp'
======================================================================== [FAILED] Took 2.28 seconds ===========================================

**Comment by dbambus** [comment]
Hallo @SkylightXD 

Das ist schon eine Weile her, wurde das Problem inzwischen gelöst? Es sieht so aus, als hättest du für den einen oder anderen Vorgang nicht die notwendigen Rechte gehabt. `[Errno 13] Permission denied`

Mit freundlichen Grüßen
David
